version: 0.1.{build}
configuration: Release

image: Visual Studio 2017

clone_depth: 1  

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'

before_build:
  - cmd: dotnet restore

build:
  parallel: true
  publish_nuget: true
  verbosity: minimal

test:
  assemblies: '**\*.Tests.dll'

deploy: off
