version: 0.1.{build}
configuration: Release

image: Visual Studio 2017

clone_depth: 1  

environment:
  AZURE_STORAGE_ACCOUNT_CONNECTION_STRING:
    secure: 0boXXDb2lYyb8gNb+bLgPCU+0N9snwKFqv8kFpD+7lNGyZkqq4Yri3v6LlKhn5v3GQ23EtKqMyzh3K8qy4WgO1ZK3oAHTgMo6xepq4rRkS1dXlWbFp9eOGjUDg+XLVH01pAMZV+wRVs5t9KnUudUA8HNj48qfmni2yf+0BHe9oF9I5S7ZpL1PvBQlTg/lnUnTbc0mI3BYXO5DShkADnwwSGe5kF2Ln0e+ZFbgJSm3goKwGOnS+Swe4nVzwSmmlo9UwxDRvlpdS+DVgDw0J2I/w==
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'

before_build:
  - cmd: dotnet restore

build:
  parallel: true
  publish_nuget: true
  verbosity: minimal

test:
  assemblies: '**\*.Test.dll'

deploy: off
